version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: localhost:5000
  secret: secret
  headers:
    X-Content-Type-Options: [nosniff]
#  tls:
#    certificate: /etc/registry/cert.pem
#    key: /etc/registry/key.pem
#auth:
#  htpasswd:
#    realm: basic-realm
#    path: /etc/registry/htpasswd
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
